---
title: "C1_H_Imputed_POS"
author: "Ali Soufizadeh"
date: "06/04/2022"
output: html_document
---


```{r include=FALSE}
# Load packages
pacman::p_load(pacman, tidyverse, kableExtra, psych, lavaan, corrplot, performance, MVN, ICS, dplyr,
               matrixStats, semPlot, gridExtra,knitr, readxl, papaja, report, mice, VIM, rmarkdown, janitor)
```

```{r}
scored_data <- read_csv("scored_data_imputed.csv")
```

# Summary of cleaned data 
```{r}
# Missing Data & outliers checked
describe(scored_data)
```


```{r}
# Rename variables for convenience in modelling
analyze_data <- scored_data %>% mutate(rename(scored_data,
                                "X" = "mean_cra", 
                                "Y" = "sum_cesd",
                                "W" = "SES",
                                "Z" = "mean_bsm",
                                "COV" = "mean_pss",
                                "M" = "sum_pos"))
```

Create interaction terms
```{r}
# Create interaction terms
analyze_data <- analyze_data %>% mutate(X.W = X * W,
                        X.Z = X * Z,
                        W.Z = W * Z,
                        X.W.Z = X * W * Z)
```


# Hypotheses C1 & C2: Moderated Mediation
```{r}
# The Model
MOD.MED.model.Latent <-
"
# Define latent nediator
Mi =~ MCQ1 + MCQ7 + MCQ10 + MCQ19 + MCQ23 + MCQ28

# Mediator
Mi ~ a*X

# Outcome being predicted by the model
Y ~ d*COV + c1*X + c2*W + c3*Z + c4*X.W + c5*X.Z + c6*W.Z + c7*X.W.Z + b1*Mi

# Covariance: Let all variables covary

# intercept
Y ~ c0 * 1

# Intercepts and variance for conditional effects analysis
W ~ W.mean*1
Z ~ Z.mean*1
X.W ~ ic4*1
X.Z ~ ic5*1
W.Z ~ ic6*1
X.W.Z ~ ic7*1

# variances for conditional effects analysis
W ~~ W.var * W
Z ~~ Z.var * Z
X.W ~~ var.c4 * X.W
X.Z ~~ var.c5 * X.Z
W.Z ~~ var.c6 * W.Z
X.W.Z ~~ var.c7* X.W.Z

# interaction terms for simple slopes
INT_LwLz := (W.mean - sqrt(W.var))*(Z.mean - sqrt(Z.var))
INT_LwHz := (W.mean - sqrt(W.var))*(Z.mean + sqrt(Z.var))
INT_HwLz := (W.mean + sqrt(W.var))*(Z.mean - sqrt(Z.var))
INT_HwHz := (W.mean + sqrt(W.var))*(Z.mean + sqrt(Z.var))

# Indirect effect of X on Y through M, conditional on mean values of W and Z
indirect := a * b1

# Direct effect of X on Y, moderated by W and Z
direct := c1 + c4 + c5 + c7

# Total effect
total := direct + indirect

# Proportion of effect mediated
prop.mediated := indirect / total

# Conditional direct effect moderated by W and Z
direct.Mean:=c1 + c4*(W.mean) + c5*(Z.mean)+ c7*ic6
direct.LwLz:=c1 + c4*(W.mean - sqrt(W.var)) + c5*(Z.mean - sqrt(Z.var)) + c7*INT_LwLz
direct.LwHz:=c1 + c4*(W.mean + sqrt(W.var)) + c5*(Z.mean + sqrt(Z.var)) + c7*INT_LwHz
direct.HwLz:=c1 + c4*(W.mean - sqrt(W.var)) + c5*(Z.mean - sqrt(Z.var)) + c7*INT_HwLz
direct.HwHz:=c1 + c4*(W.mean + sqrt(W.var)) + c5*(Z.mean + sqrt(Z.var)) + c7*INT_HwHz
"
```


```{r}
# Fit the model
Mod.Med.SEM <- sem(model = MOD.MED.model.Latent,
                   data = analyze_data,
                   se = "bootstrap",
                   test = "bootstrap",
                   bootstrap = 5000) # do 5000 when actually running the code
```


```{r}
# Model summary
summary(Mod.Med.SEM, fit.measures = FALSE, standardize = TRUE, rsquare = TRUE)
```

```{r}
# Parameters table
parameterEstimates(Mod.Med.SEM, remove.nonfree = TRUE, ci = TRUE, 
                   boot.ci.type = "perc", pvalue = TRUE, output = "pretty")
```

# Standardized parameters
```{r}
std_sols <- standardizedsolution(Mod.Med.SEM)
```

# Paths plot: C1 Y ~ sum_pos
```{r}
# Plot model
plot = semPaths(Mod.Med.SEM, fixedStyle = 1, layout = "tree2", whatLabels = "est",
                  intercepts = F, label.scale=T, nCharNodes = 5, 
                  sizeMan2=3, sizeMan=6, asize=2, residuals = F, exoCov = F)
```

```{r}
vcov(Mod.Med.SEM)
```

```{r}
describe(analyze_data)
```

